-   id: prettier
    name: prettier
    entry: prettier --write
    language: node
    files: "\\.(\
    css|less|scss\
    |graphql|gql\
    |html\
    |js|jsx\
    |json\
    |md|markdown|mdown|mkdn\
    |mdx\
    |ts|tsx\
    |vue\
    |yaml|yml\
    )$"


    # Use additional_dependencies to install the actual node package
    minimum_pre_commit_version: 0.12.0
